// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/ConnectionRequestPacket.hpp"
namespace tetriq {
ConnectionRequestPacket::ConnectionRequestPacket(std::string player_name, std::array<char, 3> color, uint64_t protocol_version)
	:player_name(player_name)
	,color(color)
	,protocol_version(protocol_version)
{}
ConnectionRequestPacket::ConnectionRequestPacket(NetworkIStream &is)
	:player_name(is.read<std::string>())
	,color(is.read<std::array<char, 3>>())
	,protocol_version(is.read<uint64_t>())
{}
size_t ConnectionRequestPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(player_name) + NetworkObject::getNetworkSize(color) + NetworkObject::getNetworkSize(protocol_version);
}
NetworkOStream &ConnectionRequestPacket::write(NetworkOStream &stream) const {
	return stream << player_name << color << protocol_version;
}
NetworkIStream &ConnectionRequestPacket::read(NetworkIStream &stream) {
	return stream >> player_name >> color >> protocol_version;
}
PacketId ConnectionRequestPacket::getId() const {
	return PacketId::CONNECTION_REQUEST;
}
}
