// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/ConnectionReplyPacket.hpp"
namespace tetriq {
ConnectionReplyPacket::ConnectionReplyPacket(bool connection_validated)
	:connection_validated(connection_validated)
{}
ConnectionReplyPacket::ConnectionReplyPacket(NetworkIStream &is)
	:connection_validated(is.read<bool>())
{}
size_t ConnectionReplyPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(connection_validated);
}
NetworkOStream &ConnectionReplyPacket::write(NetworkOStream &stream) const {
	return stream << connection_validated;
}
NetworkIStream &ConnectionReplyPacket::read(NetworkIStream &stream) {
	return stream >> connection_validated;
}
PacketId ConnectionReplyPacket::getId() const {
	return PacketId::CONNECTION_REPLY;
}
}
