// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/DestroyEntityPacket.hpp"
namespace tetriq {
DestroyEntityPacket::DestroyEntityPacket(uint64_t id)
	:id(id)
{}
DestroyEntityPacket::DestroyEntityPacket(NetworkIStream &is)
	:id(is.read<uint64_t>())
{}
size_t DestroyEntityPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(id);
}
NetworkOStream &DestroyEntityPacket::write(NetworkOStream &stream) const {
	return stream << id;
}
NetworkIStream &DestroyEntityPacket::read(NetworkIStream &stream) {
	return stream >> id;
}
PacketId DestroyEntityPacket::getId() const {
	return PacketId::DESTROY_ENTITY;
}
}
