// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/EndGamePacket.hpp"
namespace tetriq {
EndGamePacket::EndGamePacket()
{}
EndGamePacket::EndGamePacket(NetworkIStream &is)
{}
size_t EndGamePacket::getNetworkSize() const {
	return 0;
}
NetworkOStream &EndGamePacket::write(NetworkOStream &stream) const {
	return stream;
}
NetworkIStream &EndGamePacket::read(NetworkIStream &stream) {
	return stream;
}
PacketId EndGamePacket::getId() const {
	return PacketId::END_GAME;
}
}
