// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/FullSynchronisationPacket.hpp"
namespace tetriq {
FullSynchronisationPacket::FullSynchronisationPacket(uint64_t player_id, Position player_position)
	:player_id(player_id)
	,player_position(player_position)
{}
FullSynchronisationPacket::FullSynchronisationPacket(NetworkIStream &is)
	:player_id(is.read<uint64_t>())
	,player_position(is.read<Position>())
{}
size_t FullSynchronisationPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(player_id) + NetworkObject::getNetworkSize(player_position);
}
NetworkOStream &FullSynchronisationPacket::write(NetworkOStream &stream) const {
	return stream << player_id << player_position;
}
NetworkIStream &FullSynchronisationPacket::read(NetworkIStream &stream) {
	return stream >> player_id >> player_position;
}
PacketId FullSynchronisationPacket::getId() const {
	return PacketId::FULL_SYNCHRONISATION;
}
}
