// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/MovementActionPacket.hpp"
namespace tetriq {
MovementActionPacket::MovementActionPacket(Position new_pos)
	:new_pos(new_pos)
{}
MovementActionPacket::MovementActionPacket(NetworkIStream &is)
	:new_pos(is.read<Position>())
{}
size_t MovementActionPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(new_pos);
}
NetworkOStream &MovementActionPacket::write(NetworkOStream &stream) const {
	return stream << new_pos;
}
NetworkIStream &MovementActionPacket::read(NetworkIStream &stream) {
	return stream >> new_pos;
}
PacketId MovementActionPacket::getId() const {
	return PacketId::MOVEMENT_ACTION;
}
}
