// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/NewShootPacket.hpp"
namespace tetriq {
NewShootPacket::NewShootPacket(uint64_t id, Position position, Velocity velocity)
	:id(id)
	,position(position)
	,velocity(velocity)
{}
NewShootPacket::NewShootPacket(NetworkIStream &is)
	:id(is.read<uint64_t>())
	,position(is.read<Position>())
	,velocity(is.read<Velocity>())
{}
size_t NewShootPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(id) + NetworkObject::getNetworkSize(position) + NetworkObject::getNetworkSize(velocity);
}
NetworkOStream &NewShootPacket::write(NetworkOStream &stream) const {
	return stream << id << position << velocity;
}
NetworkIStream &NewShootPacket::read(NetworkIStream &stream) {
	return stream >> id >> position >> velocity;
}
PacketId NewShootPacket::getId() const {
	return PacketId::NEW_SHOOT;
}
}
