// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/PingPacket.hpp"
namespace tetriq {
PingPacket::PingPacket(time_t time)
	:time(time)
{}
PingPacket::PingPacket(NetworkIStream &is)
	:time(is.read<time_t>())
{}
size_t PingPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(time);
}
NetworkOStream &PingPacket::write(NetworkOStream &stream) const {
	return stream << time;
}
NetworkIStream &PingPacket::read(NetworkIStream &stream) {
	return stream >> time;
}
PacketId PingPacket::getId() const {
	return PacketId::PING;
}
}
