// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/QueryRequestPacket.hpp"
namespace tetriq {
QueryRequestPacket::QueryRequestPacket()
{}
QueryRequestPacket::QueryRequestPacket(NetworkIStream &is)
{}
size_t QueryRequestPacket::getNetworkSize() const {
	return 0;
}
NetworkOStream &QueryRequestPacket::write(NetworkOStream &stream) const {
	return stream;
}
NetworkIStream &QueryRequestPacket::read(NetworkIStream &stream) {
	return stream;
}
PacketId QueryRequestPacket::getId() const {
	return PacketId::S_QUERY_REQUEST;
}
}
