// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/ServerListRequestPacket.hpp"
namespace tetriq {
ServerListRequestPacket::ServerListRequestPacket()
{}
ServerListRequestPacket::ServerListRequestPacket(NetworkIStream &is)
{}
size_t ServerListRequestPacket::getNetworkSize() const {
	return 0;
}
NetworkOStream &ServerListRequestPacket::write(NetworkOStream &stream) const {
	return stream;
}
NetworkIStream &ServerListRequestPacket::read(NetworkIStream &stream) {
	return stream;
}
PacketId ServerListRequestPacket::getId() const {
	return PacketId::C_SERVER_LIST_REQUEST;
}
}
