// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/SetHealthPacket.hpp"
namespace tetriq {
SetHealthPacket::SetHealthPacket(double health, double max_health)
	:health(health)
	,max_health(max_health)
{}
SetHealthPacket::SetHealthPacket(NetworkIStream &is)
	:health(is.read<double>())
	,max_health(is.read<double>())
{}
size_t SetHealthPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(health) + NetworkObject::getNetworkSize(max_health);
}
NetworkOStream &SetHealthPacket::write(NetworkOStream &stream) const {
	return stream << health << max_health;
}
NetworkIStream &SetHealthPacket::read(NetworkIStream &stream) {
	return stream >> health >> max_health;
}
PacketId SetHealthPacket::getId() const {
	return PacketId::SET_HEALTH;
}
}
