// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/SetScorePacket.hpp"
namespace tetriq {
SetScorePacket::SetScorePacket(uint64_t score)
	:score(score)
{}
SetScorePacket::SetScorePacket(NetworkIStream &is)
	:score(is.read<uint64_t>())
{}
size_t SetScorePacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(score);
}
NetworkOStream &SetScorePacket::write(NetworkOStream &stream) const {
	return stream << score;
}
NetworkIStream &SetScorePacket::read(NetworkIStream &stream) {
	return stream >> score;
}
PacketId SetScorePacket::getId() const {
	return PacketId::SET_SCORE;
}
}
