// This file was auto-generated by generate-packets.scm, do not modify it manually.
#include "network/packets/ShootActionPacket.hpp"
namespace tetriq {
ShootActionPacket::ShootActionPacket(Position origin)
	:origin(origin)
{}
ShootActionPacket::ShootActionPacket(NetworkIStream &is)
	:origin(is.read<Position>())
{}
size_t ShootActionPacket::getNetworkSize() const {
	return 0 + NetworkObject::getNetworkSize(origin);
}
NetworkOStream &ShootActionPacket::write(NetworkOStream &stream) const {
	return stream << origin;
}
NetworkIStream &ShootActionPacket::read(NetworkIStream &stream) {
	return stream >> origin;
}
PacketId ShootActionPacket::getId() const {
	return PacketId::SHOOT_ACTION;
}
}
