// This file was auto-generated by generate-packets.scm, do not modify it manually.
#pragma once

#include "network/APacket.hpp"
#include "network/Types.hpp"

namespace tetriq {
	class ConnectionRequestPacket : public APacket {
	public:
		ConnectionRequestPacket(std::string player_name, std::array<char, 3> color, uint64_t protocol_version);
		ConnectionRequestPacket(NetworkIStream &is);

		PacketId getId() const override;
		size_t getNetworkSize() const override;
		// variables
		std::string player_name;
		std::array<char, 3> color;
		uint64_t protocol_version;

	protected:
		NetworkOStream &write(NetworkOStream &os) const override;
		NetworkIStream &read(NetworkIStream &is) override;
	};
}
