// This file was auto-generated by generate-packets.scm, do not modify it manually.
#pragma once

#include "network/APacket.hpp"
#include "network/Types.hpp"

namespace tetriq {
	class ShootPacket : public APacket {
	public:
		ShootPacket(Position origin);
		ShootPacket(NetworkIStream &is);

		size_t getNetworkSize() const override;
		// variables
		Position origin;

	protected:
		NetworkOStream &write(NetworkOStream &os) const override;
		NetworkIStream &read(NetworkIStream &is) override;
		PacketId getId() const override;
	};
}
